Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_BUSINESS-INDUSTRY/PyAF_M4_COMP_BUSINESS-INDUSTRY_B&IND0434_26.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_BUSINESS-INDUSTRY/PyAF_M4_COMP_BUSINESS-INDUSTRY_B&IND0434_26.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_BUSINESS-INDUSTRY
TIME :  Date N= 156 H= 26 HEAD= [0 1 2 3 4] TAIL= [151 152 153 154 155]
SIGNAL :  B&IND0448 N= 156 H= 26 HEAD= [1160. 1533. 1315. 1496. 1499.] TAIL= [1296. 1277. 1175. 1530.  817.]
   B&IND0448  Date
0     1160.0     0
1     1533.0     1
2     1315.0     2
3     1496.0     3
4     1499.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 156 entries, 0 to 155
Data columns (total 2 columns):
B&IND0448    156 non-null float64
Date         156 non-null int64
dtypes: float64(1), int64(1)
memory usage: 3.7 KB
None
BENCHMARK_FAILURE 'M4_COMP_BUSINESS-INDUSTRY_B&IND0448_26'
