Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_BUSINESS-INDUSTRY/PyAF_M4_COMP_BUSINESS-INDUSTRY_B&IND0005_26.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_BUSINESS-INDUSTRY/PyAF_M4_COMP_BUSINESS-INDUSTRY_B&IND0005_26.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_BUSINESS-INDUSTRY
TIME :  Date N= 104 H= 26 HEAD= [0 1 2 3 4] TAIL= [ 99 100 101 102 103]
SIGNAL :  B&IND0023 N= 104 H= 26 HEAD= [5386. 6903. 7621. 7282. 6703.] TAIL= [7142. 7721. 7721. 7116. 5284.]
   B&IND0023  Date
0     5386.0     0
1     6903.0     1
2     7621.0     2
3     7282.0     3
4     6703.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 104 entries, 0 to 103
Data columns (total 2 columns):
B&IND0023    104 non-null float64
Date         104 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.4 KB
None
BENCHMARK_FAILURE 'M4_COMP_BUSINESS-INDUSTRY_B&IND0023_26'
