Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M3_M_COMP/PyAF_M3_M_COMP_N2428_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M3_M_COMP/PyAF_M3_M_COMP_N2428_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M3_M_COMP
TIME :  Date N= 116 H= 18 HEAD= [0 1 2 3 4] TAIL= [111 112 113 114 115]
SIGNAL :  N2441 N= 116 H= 18 HEAD= [3477.8 3513.3 3544.  3576.7 3588.3] TAIL= [4184.5 4187.2 4189.5 4190.8 4202.7]
Index   N2441  Date
1      3477.8     0
2      3513.3     1
3      3544.0     2
4      3576.7     3
5      3588.3     4
<class 'pandas.core.frame.DataFrame'>
Index: 116 entries, 1 to 116
Data columns (total 2 columns):
N2441    116 non-null float64
Date     116 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.7+ KB
None
BENCHMARK_FAILURE 'M3_M_COMP_N2441_18'
