Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M3_M_COMP/PyAF_M3_M_COMP_N1538_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M3_M_COMP/PyAF_M3_M_COMP_N1538_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M3_M_COMP
TIME :  Date N= 51 H= 18 HEAD= [0 1 2 3 4] TAIL= [46 47 48 49 50]
SIGNAL :  N1552 N= 51 H= 18 HEAD= [3400. 2400. 4450. 2750. 3250.] TAIL= [3350. 5100. 4150. 3500. 4950.]
Index   N1552  Date
1      3400.0     0
2      2400.0     1
3      4450.0     2
4      2750.0     3
5      3250.0     4
<class 'pandas.core.frame.DataFrame'>
Index: 51 entries, 1 to 51
Data columns (total 2 columns):
N1552    51 non-null float64
Date     51 non-null int64
dtypes: float64(1), int64(1)
memory usage: 1.2+ KB
None
BENCHMARK_FAILURE 'M3_M_COMP_N1552_18'
