Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0246_35.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0246_35.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_CLIMATE
TIME :  Date N= 1064 H= 35 HEAD= [0 1 2 3 4] TAIL= [1059 1060 1061 1062 1063]
SIGNAL :  C0259 N= 1064 H= 35 HEAD= [1024. 1018. 1013. 1013. 1013.] TAIL= [1011. 1006. 1005. 1008. 1009.]
    C0259  Date
0  1024.0     0
1  1018.0     1
2  1013.0     2
3  1013.0     3
4  1013.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1064 entries, 0 to 1063
Data columns (total 2 columns):
C0259    1064 non-null float64
Date     1064 non-null int64
dtypes: float64(1), int64(1)
memory usage: 24.9 KB
None
BENCHMARK_FAILURE 'M4_COMP_CLIMATE_C0259_35'
