Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0501_35.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0501_35.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_CLIMATE
TIME :  Date N= 416 H= 35 HEAD= [0 1 2 3 4] TAIL= [411 412 413 414 415]
SIGNAL :  C0516 N= 416 H= 35 HEAD= [998. 996. 996. 982. 979.] TAIL= [1015. 1019. 1010. 1005. 1020.]
   C0516  Date
0  998.0     0
1  996.0     1
2  996.0     2
3  982.0     3
4  979.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 416 entries, 0 to 415
Data columns (total 2 columns):
C0516    416 non-null float64
Date     416 non-null int64
dtypes: float64(1), int64(1)
memory usage: 9.8 KB
None
BENCHMARK_FAILURE 'M4_COMP_CLIMATE_C0516_35'
