Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0335_35.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0335_35.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_CLIMATE
TIME :  Date N= 963 H= 35 HEAD= [0 1 2 3 4] TAIL= [958 959 960 961 962]
SIGNAL :  C0349 N= 963 H= 35 HEAD= [64. 66. 82. 89. 90.] TAIL= [89. 67. 72. 75. 89.]
   C0349  Date
0   64.0     0
1   66.0     1
2   82.0     2
3   89.0     3
4   90.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 963 entries, 0 to 962
Data columns (total 2 columns):
C0349    963 non-null float64
Date     963 non-null int64
dtypes: float64(1), int64(1)
memory usage: 22.6 KB
None
BENCHMARK_FAILURE 'M4_COMP_CLIMATE_C0349_35'
