Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0252_35.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_CLIMATE/PyAF_M4_COMP_CLIMATE_C0252_35.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_CLIMATE
TIME :  Date N= 1019 H= 35 HEAD= [0 1 2 3 4] TAIL= [1014 1015 1016 1017 1018]
SIGNAL :  C0264 N= 1019 H= 35 HEAD= [1007. 1013.  995. 1003. 1008.] TAIL= [1017. 1015. 1017. 1005. 1010.]
    C0264  Date
0  1007.0     0
1  1013.0     1
2   995.0     2
3  1003.0     3
4  1008.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1019 entries, 0 to 1018
Data columns (total 2 columns):
C0264    1019 non-null float64
Date     1019 non-null int64
dtypes: float64(1), int64(1)
memory usage: 23.9 KB
None
BENCHMARK_FAILURE 'M4_COMP_CLIMATE_C0264_35'
