Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN721_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN721_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 121 H= 6 HEAD= [0 1 2 3 4] TAIL= [116 117 118 119 120]
SIGNAL :  FIN727 N= 121 H= 6 HEAD= [-0.14019808  0.00877862 -0.0924511   0.14756469  0.05358673] TAIL= [-0.06320226 -0.05368576  0.08412208 -0.13194652 -0.04800922]
     FIN727  Date
0 -0.140198     0
1  0.008779     1
2 -0.092451     2
3  0.147565     3
4  0.053587     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 121 entries, 0 to 120
Data columns (total 2 columns):
FIN727    121 non-null float64
Date      121 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.8 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN727_6'
