Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1379_19.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1379_19.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 121 H= 6 HEAD= [0 1 2 3 4] TAIL= [116 117 118 119 120]
SIGNAL :  FIN1387 N= 121 H= 6 HEAD= [ 0.1110779  -0.06484954  0.04674622  0.10663847 -0.00824407] TAIL= [-0.16634812 -0.11945248 -0.29775772  0.14031215 -0.35244064]
    FIN1387  Date
0  0.111078     0
1 -0.064850     1
2  0.046746     2
3  0.106638     3
4 -0.008244     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 121 entries, 0 to 120
Data columns (total 2 columns):
FIN1387    121 non-null float64
Date       121 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.8 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN1387_6'
