Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1820_12.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1820_12.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 464 H= 19 HEAD= [0 1 2 3 4] TAIL= [459 460 461 462 463]
SIGNAL :  FIN1826 N= 464 H= 19 HEAD= [-0.00322394 -0.01252442  0.03815177 -0.01617286  0.0222658 ] TAIL= [-0.07061757 -0.03807969  0.06014885  0.00859242 -0.06874127]
    FIN1826  Date
0 -0.003224     0
1 -0.012524     1
2  0.038152     2
3 -0.016173     3
4  0.022266     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 464 entries, 0 to 463
Data columns (total 2 columns):
FIN1826    464 non-null float64
Date       464 non-null int64
dtypes: float64(1), int64(1)
memory usage: 10.9 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN1826_19'
