Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN934_94.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN934_94.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 540 H= 19 HEAD= [0 1 2 3 4] TAIL= [535 536 537 538 539]
SIGNAL :  FIN960 N= 540 H= 19 HEAD= [ 0.02747547  0.01438874  0.02817088 -0.0719735  -0.0476863 ] TAIL= [0.08530736 0.14707608 0.02794593 0.02668627 0.06313128]
     FIN960  Date
0  0.027475     0
1  0.014389     1
2  0.028171     2
3 -0.071973     3
4 -0.047686     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 2 columns):
FIN960    540 non-null float64
Date      540 non-null int64
dtypes: float64(1), int64(1)
memory usage: 12.7 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN960_19'
