Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN776_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN776_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 217 H= 8 HEAD= [0 1 2 3 4] TAIL= [212 213 214 215 216]
SIGNAL :  FIN780 N= 217 H= 8 HEAD= [ 0.06261359 -0.01749316 -0.000596   -0.05625916  0.00124378] TAIL= [ 0.05096872  0.01524455  0.0200835  -0.03381634 -0.02173105]
     FIN780  Date
0  0.062614     0
1 -0.017493     1
2 -0.000596     2
3 -0.056259     3
4  0.001244     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 217 entries, 0 to 216
Data columns (total 2 columns):
FIN780    217 non-null float64
Date      217 non-null int64
dtypes: float64(1), int64(1)
memory usage: 5.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN780_8'
