Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN946_94.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN946_94.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 540 H= 19 HEAD= [0 1 2 3 4] TAIL= [535 536 537 538 539]
SIGNAL :  FIN969 N= 540 H= 19 HEAD= [ 0.0159439   0.0069745  -0.00529618 -0.02561884 -0.04306465] TAIL= [ 0.13491127  0.02242996 -0.04735184  0.06303752  0.06082956]
     FIN969  Date
0  0.015944     0
1  0.006975     1
2 -0.005296     2
3 -0.025619     3
4 -0.043065     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 2 columns):
FIN969    540 non-null float64
Date      540 non-null int64
dtypes: float64(1), int64(1)
memory usage: 12.7 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN969_19'
