Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1973_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1973_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 121 H= 6 HEAD= [0 1 2 3 4] TAIL= [116 117 118 119 120]
SIGNAL :  FIN1983 N= 121 H= 6 HEAD= [ 0.12676519 -0.09095278  0.07303911  0.03255914 -0.02886078] TAIL= [-0.12377981 -0.19518672 -0.11397482  0.02664168 -0.06592309]
    FIN1983  Date
0  0.126765     0
1 -0.090953     1
2  0.073039     2
3  0.032559     3
4 -0.028861     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 121 entries, 0 to 120
Data columns (total 2 columns):
FIN1983    121 non-null float64
Date       121 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.8 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN1983_6'
