Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN353_30.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN353_30.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 113 H= 4 HEAD= [0 1 2 3 4] TAIL= [108 109 110 111 112]
SIGNAL :  FIN365 N= 113 H= 4 HEAD= [-0.20187693  0.09252803  0.06605028 -0.02051686 -0.10165802] TAIL= [ 0.001443   -0.08865131 -0.05617027  0.04375103  0.06659702]
     FIN365  Date
0 -0.201877     0
1  0.092528     1
2  0.066050     2
3 -0.020517     3
4 -0.101658     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 113 entries, 0 to 112
Data columns (total 2 columns):
FIN365    113 non-null float64
Date      113 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.6 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN365_4'
