Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN686_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN686_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 540 H= 19 HEAD= [0 1 2 3 4] TAIL= [535 536 537 538 539]
SIGNAL :  FIN693 N= 540 H= 19 HEAD= [0.02794593 0.09387751 0.11179141 0.06056429 0.13660378] TAIL= [ 0.05396756  0.0507165  -0.06127953 -0.00884501  0.05366831]
     FIN693  Date
0  0.027946     0
1  0.093878     1
2  0.111791     2
3  0.060564     3
4  0.136604     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 2 columns):
FIN693    540 non-null float64
Date      540 non-null int64
dtypes: float64(1), int64(1)
memory usage: 12.7 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN693_19'
