Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1240_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1240_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 121 H= 6 HEAD= [0 1 2 3 4] TAIL= [116 117 118 119 120]
SIGNAL :  FIN1246 N= 121 H= 6 HEAD= [ 0.18276709  0.11157723  0.00430678  0.07358836 -0.01547539] TAIL= [-0.0484291  -0.20843489 -0.30884386 -0.00347424 -0.20389838]
    FIN1246  Date
0  0.182767     0
1  0.111577     1
2  0.004307     2
3  0.073588     3
4 -0.015475     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 121 entries, 0 to 120
Data columns (total 2 columns):
FIN1246    121 non-null float64
Date       121 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.8 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN1246_6'
