Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1228_19.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1228_19.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 121 H= 6 HEAD= [0 1 2 3 4] TAIL= [116 117 118 119 120]
SIGNAL :  FIN1237 N= 121 H= 6 HEAD= [ 0.5230692  -0.07697536  0.18701353  0.08626299  0.0861777 ] TAIL= [-0.21565288 -0.33089083 -0.36225635  0.20507077 -0.03400637]
    FIN1237  Date
0  0.523069     0
1 -0.076975     1
2  0.187014     2
3  0.086263     3
4  0.086178     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 121 entries, 0 to 120
Data columns (total 2 columns):
FIN1237    121 non-null float64
Date       121 non-null int64
dtypes: float64(1), int64(1)
memory usage: 2.8 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN1237_6'
