Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN9_65.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN9_65.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 2345 H= 84 HEAD= [0 1 2 3 4] TAIL= [2340 2341 2342 2343 2344]
SIGNAL :  FIN31 N= 2345 H= 84 HEAD= [7.7765 7.7775 7.778  7.7785 7.7783] TAIL= [7.7505 7.75   7.75   7.7495 7.75  ]
    FIN31  Date
0  7.7765     0
1  7.7775     1
2  7.7780     2
3  7.7785     3
4  7.7783     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2345 entries, 0 to 2344
Data columns (total 2 columns):
FIN31    2345 non-null float64
Date     2345 non-null int64
dtypes: float64(1), int64(1)
memory usage: 55.0 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN31_84'
