Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1366_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN1366_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 540 H= 19 HEAD= [0 1 2 3 4] TAIL= [535 536 537 538 539]
SIGNAL :  FIN1370 N= 540 H= 19 HEAD= [-0.05406722  0.12516314  0.03373814 -0.07374347  0.07374347] TAIL= [0.05954139 0.07125962 0.06203089 0.00895361 0.05157181]
    FIN1370  Date
0 -0.054067     0
1  0.125163     1
2  0.033738     2
3 -0.073743     3
4  0.073743     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 2 columns):
FIN1370    540 non-null float64
Date       540 non-null int64
dtypes: float64(1), int64(1)
memory usage: 12.7 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN1370_19'
