Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN159_6.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN159_6.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 540 H= 19 HEAD= [0 1 2 3 4] TAIL= [535 536 537 538 539]
SIGNAL :  FIN163 N= 540 H= 19 HEAD= [ 0.00740854 -0.01637185 -0.07346177 -0.06436627 -0.04906578] TAIL= [ 0.08981982  0.03863641 -0.08154688 -0.00099133  0.04342708]
     FIN163  Date
0  0.007409     0
1 -0.016372     1
2 -0.073462     2
3 -0.064366     3
4 -0.049066     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 540 entries, 0 to 539
Data columns (total 2 columns):
FIN163    540 non-null float64
Date      540 non-null int64
dtypes: float64(1), int64(1)
memory usage: 12.7 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN163_19'
