Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN423_63.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN423_63.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 344 H= 12 HEAD= [0 1 2 3 4] TAIL= [339 340 341 342 343]
SIGNAL :  FIN440 N= 344 H= 12 HEAD= [ 0.0380559  -0.07395566 -0.0375529  -0.08305166  0.08399997] TAIL= [-0.05322647 -0.00461143  0.06219074  0.033416   -0.03982381]
     FIN440  Date
0  0.038056     0
1 -0.073956     1
2 -0.037553     2
3 -0.083052     3
4  0.084000     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 344 entries, 0 to 343
Data columns (total 2 columns):
FIN440    344 non-null float64
Date      344 non-null int64
dtypes: float64(1), int64(1)
memory usage: 8.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN440_12'
