Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN345_83.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_FINANCE/PyAF_M4_COMP_FINANCE_FIN345_83.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_FINANCE
TIME :  Date N= 344 H= 12 HEAD= [0 1 2 3 4] TAIL= [339 340 341 342 343]
SIGNAL :  FIN370 N= 344 H= 12 HEAD= [ 0.0522092  -0.02863045 -0.04560376 -0.07255929  0.04967663] TAIL= [-0.05503191  0.04015068  0.07541896  0.05970412  0.07504308]
     FIN370  Date
0  0.052209     0
1 -0.028630     1
2 -0.045604     2
3 -0.072559     3
4  0.049677     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 344 entries, 0 to 343
Data columns (total 2 columns):
FIN370    344 non-null float64
Date      344 non-null int64
dtypes: float64(1), int64(1)
memory usage: 8.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_FINANCE_FIN370_12'
