Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_INTERNET-TELECOM/PyAF_M4_COMP_INTERNET-TELECOM_I&T0026_26.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_INTERNET-TELECOM/PyAF_M4_COMP_INTERNET-TELECOM_I&T0026_26.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_INTERNET-TELECOM
TIME :  Date N= 261 H= 26 HEAD= [0 1 2 3 4] TAIL= [256 257 258 259 260]
SIGNAL :  I&T0039 N= 261 H= 26 HEAD= [134. 133. 132. 132. 107.] TAIL= [75. 74. 73. 78. 85.]
   I&T0039  Date
0    134.0     0
1    133.0     1
2    132.0     2
3    132.0     3
4    107.0     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 261 entries, 0 to 260
Data columns (total 2 columns):
I&T0039    261 non-null float64
Date       261 non-null int64
dtypes: float64(1), int64(1)
memory usage: 6.1 KB
None
BENCHMARK_FAILURE 'M4_COMP_INTERNET-TELECOM_I&T0039_26'
